### ISSUE TITLE
Inglisekeelne nimetus

### ISSUE THREAD

**Issue by edmundlaugasson** [alvatal/alvatal.github.io#11]
Alvatali kodulehel paistab läbisegi olema "Estonian Free and Open-Source Software Association" ja "Estonian Free and Open-Source Software Alliance". Peaks ühe ära valima & edaspidi vaid seda kasutama. Ma ise olen "... Alliance" nime autor.

**Comment by v6sa** [comment]
https://github.com/alvatal/alvatal.github.io/pull/7 see teema on juba läbi käinud ning vastuväiteid ei olnud
